version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: sdgapp-mysql
    restart: unless-stopped
    env_file: # Tell Docker Compose to look at Laravel .env file for variable substitution
      - ./laravel/.env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - sdgapp_net

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile.prod # Production Dockerfile
      target: php_env
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: sdg-php
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "cgi-fcgi", "-bind", "-connect", "127.0.0.1:9000"]
      interval: 10s
      timeout: 3s
      retries: 5
    depends_on:
      - mysql
    networks:
      - sdgapp_net
    env_file:
      - ./laravel/.env
    volumes:
      - laravel_storage:/var/www/laravel/storage
      - laravel_public:/var/www/laravel/public

  nginx:
    build:
      context: .
      dockerfile: docker/php/Dockerfile.prod
      target: nginx_env
    container_name: sdg-nginx
    restart: unless-stopped
    ports:
      - "80:80" # Public HTTP
      - "443:443"
    depends_on:
      php:
        condition: service_healthy
    volumes:
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro # SSL certificates
      - laravel_storage:/var/www/laravel/storage
      - laravel_public:/var/www/laravel/public
    networks:
      - sdgapp_net

networks:
  sdgapp_net:

volumes:
  mysql_data:
  laravel_storage:
  laravel_public:
